version: "3.9"

services:
  db:
    image: postgres:14
    container_name: json_postgres
    environment:
      POSTGRES_DB: jsondb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    container_name: json_service
    depends_on:
      - db
    environment:
      MODE: ${MODE}
      FERNET_KEY: ${FERNET_KEY}
      DB_DSN: ${DB_DSN}
    volumes:
      - .:/app
    working_dir: /app
    command: ["./main"]

volumes:
  pgdata:
